name: Run Server Script  

on:
  # Schedule to run every hour (Adjust using cron syntax)
  schedule:
    - cron: '0 * * * *'
  # Allows you to manually trigger it from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          ACCESS_KEY: "D6CCE35C-487A-458F-BAB2-9032C2621F38"
          GZIP_METHOD: "transform"
        run: node server.js
