name: Run Server Script  

on:
  # Schedule to run every hour (Adjust using cron syntax)
  schedule:
    - cron: '0 * * * *'
  # Allows you to manually trigger it from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          # Automatically detects and pulls the active branch name
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          PORT: ${{ secrets.PORT }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          GZIP_METHOD: "transform"
        run: node server.js
